version: "3.8"

services:
  test_web_app:
    container_name: "test_web_app"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: >
      sh -c "
        echo "Starting..."
        pytest
      "
    networks:
      - test_network


networks:
  test_network:
    external:
      name: web_network