"""Menu and submenu

Revision ID: 01440db938ff
Revises: e179f13743ca
Create Date: 2023-01-17 16:39:39.451528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01440db938ff'
down_revision = 'e179f13743ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('submenu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'submenus', ['submenu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'submenu_id')
    # ### end Alembic commands ###
