"""Menu aremove relation and set integer

Revision ID: 08e1a7c175e3
Revises: 2048c6781cd1
Create Date: 2023-01-17 19:40:17.038537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e1a7c175e3'
down_revision = '2048c6781cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
