"""Menu and submenu

Revision ID: 307a8d21b6f1
Revises: 01440db938ff
Create Date: 2023-01-17 17:40:53.967788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307a8d21b6f1'
down_revision = '01440db938ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menus_submenu_id_fkey', 'menus', type_='foreignkey')
    op.drop_column('menus', 'submenu_id')
    op.add_column('submenus', sa.Column('menu_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'submenus', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.drop_column('submenus', 'menu_id')
    op.add_column('menus', sa.Column('submenu_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('menus_submenu_id_fkey', 'menus', 'submenus', ['submenu_id'], ['id'])
    # ### end Alembic commands ###
