"""unique dish

Revision ID: 56e02843d821
Revises: 9055a5b4aec9
Create Date: 2023-01-17 23:37:14.808705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e02843d821'
down_revision = '9055a5b4aec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dishes_title', table_name='dishes')
    op.create_index(op.f('ix_dishes_title'), 'dishes', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dishes_title'), table_name='dishes')
    op.create_index('ix_dishes_title', 'dishes', ['title'], unique=False)
    # ### end Alembic commands ###
