"""add dishes_count

Revision ID: 5969a93422d9
Revises: 676d0d47988f
Create Date: 2023-01-18 04:03:26.224749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5969a93422d9'
down_revision = '676d0d47988f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
