"""another problems

Revision ID: 6c0a4c36b253
Revises: 77b7bbd1e7da
Create Date: 2023-01-17 21:06:15.691655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0a4c36b253'
down_revision = '77b7bbd1e7da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
