"""return to unique

Revision ID: 6e02f281b722
Revises: 36de2dbe8387
Create Date: 2023-01-18 02:33:13.897754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e02f281b722'
down_revision = '36de2dbe8387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dishes_title', table_name='dishes')
    op.create_index(op.f('ix_dishes_title'), 'dishes', ['title'], unique=True)
    op.drop_index('ix_submenus_title', table_name='submenus')
    op.create_index(op.f('ix_submenus_title'), 'submenus', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submenus_title'), table_name='submenus')
    op.create_index('ix_submenus_title', 'submenus', ['title'], unique=False)
    op.drop_index(op.f('ix_dishes_title'), table_name='dishes')
    op.create_index('ix_dishes_title', 'dishes', ['title'], unique=False)
    # ### end Alembic commands ###
