"""try to dish relation

Revision ID: 9055a5b4aec9
Revises: e1501cf04dde
Create Date: 2023-01-17 22:29:13.914178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9055a5b4aec9'
down_revision = 'e1501cf04dde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('submenu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'submenus', ['submenu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'submenu_id')
    # ### end Alembic commands ###
