"""final

Revision ID: 999579ccea90
Revises: 5969a93422d9
Create Date: 2023-01-23 17:30:08.796595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999579ccea90'
down_revision = '5969a93422d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
