"""another problems

Revision ID: a4b8897e6afd
Revises: 6c0a4c36b253
Create Date: 2023-01-17 21:14:11.965109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b8897e6afd'
down_revision = '6c0a4c36b253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
