"""add menu and submenu2

Revision ID: e0838c909681
Revises: 31e1da4bc162
Create Date: 2023-01-16 18:59:04.096468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0838c909681'
down_revision = '31e1da4bc162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
