"""try to solve

Revision ID: e1501cf04dde
Revises: 8a94c36fd59b
Create Date: 2023-01-17 22:26:14.317037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1501cf04dde'
down_revision = '8a94c36fd59b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
