"""Menu aremove relation

Revision ID: f8f188f26416
Revises: 7485ee8febd2
Create Date: 2023-01-17 19:36:02.908067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f188f26416'
down_revision = '7485ee8febd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submenus_menu_id_fkey', 'submenus', type_='foreignkey')
    op.drop_column('submenus', 'menu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('menu_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('submenus_menu_id_fkey', 'submenus', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###
